services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    volumes:
      - ./ollama:/root/.ollama
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_HOST=0.0.0.0
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  miniconda:
    image: continuumio/miniconda3:latest
    container_name: miniconda3
    command: bash -c "pip install -q langchain langchain-community langchain-openai langchain_chroma tiktoken chromadb openai transformers && tail -F anything"
    restart: unless-stopped
    volumes:
      - ./conda:/root
    environment:
      - TZ=Asia/Seoul
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ./pgsql:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
